#!/usr/bin/env python2.7
# A test harness for the Dealer's feed1 method

import sys
import json
from gui.dealer import *

try:
	testInput = json.load(sys.stdin)
	if len(testInput) == 3:
		curDealer = Dealer.dealerFromJson(testInput)
		curDealer.feed1()
		result = curDealer.dealerToJson()
		print json.dumps(result)


except Exception as e:
	quit()
