#!/usr/bin/env python2.7
import sys
import socket
from server.dealer import *
from server.playerState import PlayerState
from server.proxyPlayer import ProxyPlayer
import time

TIMEOUT = 15
MIN_PLAYERS = 3
MAX_PLAYERS = 8

"""
	Create a socket and bind to the global port
	String, Nat -> Socket
"""
def setUpSock(ip, port):
	sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	sock.bind((ip, port))
	sock.listen(1)
	sock.settimeout(TIMEOUT)
	return sock

"""
	Create a server that supports the max. number of players
	Then, wait for enough players to connect and run a game
	Nat, String -> Void
"""
def main(port, ip):
	sock = setUpSock(ip, port)
	players = []
	startTime = time.time()

	while (len(players) < MIN_PLAYERS) or ((time.time() - startTime < TIMEOUT) and (len(players) < MAX_PLAYERS)): 
		try:
			conn, addr = sock.accept()
		except (socket.timeout):
			break
		info = conn.recv(512)
		conn.sendall("ok")
		player = PlayerState(len(players) + 1, 0, [], [], ProxyPlayer(conn), info)
		players.append(player) 

	time.sleep(1)
	deal = Dealer(players, 0)
	deal.runGame()


if __name__ == "__main__":
	if len(sys.argv) > 1:
		if len(sys.argv) == 3:
			ip = str(sys.argv[2])
		else:
			ip = "127.0.0.1"
		main(int(sys.argv[1]), ip)
	else:
		print "Usage: ./main-server port <OPT: IP>"
		quit()
