#!/usr/bin/env python2.7
# A test harness for the Dealer's step4 method

import sys
import json
from dealer.dealer import *
from dealer.action4 import *

try:
	testInput = json.load(sys.stdin)
	if len(testInput) == 2:
		curDealer = Dealer.dealerFromJson(testInput[0])
		jsonActions = testInput[1]
		actions = [Action4.actionFromJson(jsonActions[i], curDealer.players[i]) for i in range(len(curDealer.players))]
		curDealer.step4(actions)
		result = curDealer.dealerToJson()
		print json.dumps(result)

except Exception as e:
#	raise e
	quit()
